
const lessonsObj = {
    1: {
        id: 1,
        subject: "Math",
        imgSrc: "assets/math.png",
        imgAlt: "assets/math.png",
        location: 'London',
        price: 10,
        spaces: 5,
    },
    2: {
        id: 2,
        subject: "Chemistry",
        imgSrc: "assets/chemistry.png",
        imgAlt: "assets/chemistry.png",
        location: 'London',
        price: 7,
        spaces: 5,
    },
    3: {
        id: 3,
        subject: "Physics",
        imgSrc: "assets/physics.png",
        imgAlt: "assets/physics.png",
        location: 'London',
        price: 5,
        spaces: 5,
    },
    4: {
        id: 4,
        subject: "Geography",
        imgSrc: "assets/geography.png",
        imgAlt: "assets/geography.png",
        location: 'London',
        price: 4,
        spaces: 5,
    },
    5: {
        id: 5,
        subject: "English",
        imgSrc: "assets/geography.png",
        imgAlt: "assets/geography.png",
        location: 'Dubai',
        price: 10,
        spaces: 5,
    },
    6: {
        id: 6,
        subject: "History",
        imgSrc: "assets/history.png",
        imgAlt: "assets/history.png",
        location: 'Egypt',
        price: 7,
        spaces: 5,
    },
    7: {
        id: 7,
        subject: "Physical Ed.",
        imgSrc: "assets/pe.png",
        imgAlt: "assets/pe.png",
        location: 'U.S.A',
        price: 5,
        spaces: 5,
    },
    8: {
        id: 8,
        subject: "French",
        imgSrc: "assets/french.png",
        imgAlt: "assets/french.png",
        location: 'France',
        price: 6,
        spaces: 5,
    },
    9: {
        id: 9,
        subject: "Computer Science",
        imgSrc: "assets/computerscience.png",
        imgAlt: "assets/computerscience.png",
        location: 'Switzerland',
        price: 9,
        spaces: 5,
    },
    10: {
        id: 10,
        subject: "Music",
        imgSrc: "assets/music.png",
        imgAlt: "assets/music.png",
        location: 'Italy',
        price: 9,
        spaces: 5,
    },
}